### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by taro-taro-taro** [Malalicious/Serenity#1]
1.Could you please support multiple HP bars?

2.How do I change the search range of pixels?

**Comment by Malalicious** [comment]
To answer your first question, I am currently not developing any extra features. Anyone is free to do so and share their code/create a pull request.

Your second question is somewhat answered in the Wiki under the article [adding resolutions](https://github.com/Malalicious/Serenity/wiki/Adding-resolutions). What you're looking for is changing the FieldOfView. Take a look at the short description and the graphical representation of the field of view. Keep in mind that each module (aimbot, widowbot, anabot and triggerbot) has its own list of Fovs.
