### ISSUE TITLE
how to change smoothness?

### ISSUE THREAD

**Issue by iWonAMathsDebate** [Malalicious/Serenity#12]
Great work, only one question tho;
how do i change the smoothness of the aimbot? o.O

**Comment by dideodn83** [comment]
The current program does not have coding to adjust the mouse sensitivity
... you have to create it separately

2017-07-27 7:53 GMT+09:00 iWonAMathsDebate <notifications@github.com>:

**Comment by iWonAMathsDebate** [comment]
Alright, no problemz, i'll figure.
