### ISSUE TITLE
not really functioning!

### ISSUE THREAD

**Issue by yldn** [Malalicious/Serenity#18]
I understand basically the most part of Code mousehelper, aimbot,and i use to test firstly in Training mode, works pretty good ,but it doesn't work at all in normal search ,this issue is probably related with some of method of the screen capture.i guess it could be Overwatch team ,locking the screenshot function during the normal game search ,and allows capture for streamers to streaming.
Well,think it can't capture any image while normal game(accept training),so that  the solution doesn't work at time.

**Comment by Malalicious** [comment]
This probably means you have been screenlocked because you used other cheats before. There's nothing you can do about it as far as I know.
