### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by sparkiespaark** [Malalicious/Serenity#2]
Hey, I don't really know anything about coding or anything,

I was wondering if you could change stuff around and compile it differently? I will be willing too pay? I mean I will even pay a fair amount if you could code me one differently?

**Comment by Malalicious** [comment]
I sadly cannot offer the support that would come with a project like that such as optimization for your settings and bugfixing. I am sure some script kiddies can tear this code apart and create something "unique" though. However, if you provide me with a list of features you are expecting, I can think about it.

**Comment by sparkiespaark** [comment]
I understand :)

Well if you think about it and decide too the only things I really want is a human-smoothed aim. I honestly don't care for trigger or any ana bot or anything. Just a nice aimbot that can look very legit with like x/y axis randomize or something. Not sure what is actually possible but something like say if I aim low it will go to the body or if I aim higher towards head it will go for the neck in random spots, not sure if that is possible. With tracking which is smooth, and not shaky.

But, I am basically just want something that can be legit as possible.

**Comment by Malalicious** [comment]
Possible but like I said, I cannot offer support. If you could give me a way of contacting you I will let you know more. For now I will close this as it is not really an issue.

**Comment by sparkiespaark** [comment]
There we go haha ^^ was wondering how I could contact on here. 

But you can message me on skype @ sparkiespaark@protonmail.com
or just email me on that email also
