### ISSUE TITLE
dropbox.exe

### ISSUE THREAD

**Issue by Lassetheg** [Malalicious/Serenity#6]
where i can find dropbox.exe pls help?
and can i get banned easily

**Comment by Malalicious** [comment]
You need to compile it yourself.
As for the banning part, every cheat that's publicly available will get you banned eventually. The point is that people can learn from the code and make their own cheat.

**Comment by Lassetheg** [comment]
how can i compile it?

**Comment by Lassetheg** [comment]
and you have a video where you can show it?

**Comment by Lassetheg** [comment]
i mean the hack

**Comment by Malalicious** [comment]
I am closing this issue as this is no real issue. I am pretty sure a quick search on Google can show you how to compile a .NET solution.
