### ISSUE TITLE
I don't know how

### ISSUE THREAD

**Issue by Lassetheg** [Malalicious/Serenity#8]
Maybe im the dumbest person in the Internet, but idk how to use dropbox.exe and I don't know how to compile it

**Comment by Lassetheg** [comment]
Nice help...
Maybe you could send me dropbox.exe file cause idk how...
Have a great Day!    c:

**Comment by Malalicious** [comment]
I don't think Github is a place where you ask for help that can be googled and the answer found in seconds. These tickets you are opening are meant for reporting bugs and other issues related to the actual software. Also, next time you should read as I stated in the readme that I won't offer any support.

**Comment by Lassetheg** [comment]
okay
