### ISSUE TITLE
Can I check the HP bar width?

### ISSUE THREAD

**Issue by dideodn83** [Malalicious/Serenity#9]
Thank you very much.

As the distance goes away, the aim aiming point will go down and you can check the HP bar width separately.

If you do, the HP bar width is slightly different for each street.

When you make adjustments

Could not you add a formula to get HP bar width?

Please

And

I want to reduce the recognition range of the mouse a little, but where should I fix it?

**Comment by Malalicious** [comment]
Due to a lack of motivation I am no longer developing this cheat. I am working on a new cheat which will be private and therefor I cannot offer any support.

Perhaps look at one of the forks to see if there's active development and perhaps request this feature over there?
